#:schema node_modules/wrangler/config-schema.json
name = "cloud-drop"
main = "src/index.ts"
compatibility_date = "2024-12-05"

# 静态资源目录
assets = { directory = "./public" }

# Durable Objects 配置
[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
